extends SceneTree
const Rules = preload("res://lesson.gd")
func _initialize() -> void:
	var lesson = Rules.new()
	assert(not lesson.begin(2), "Locked stage must reject entry")
	assert(lesson.explore(0))
	assert(not lesson.explore(0))
	assert(lesson.score == 10, "A repeated pad cannot farm points")
	for i in range(1,8): lesson.explore(i)
	assert(lesson.phase == "complete" and lesson.score == 80 and lesson.unlocked() == 2)
	assert(lesson.begin(2))
	assert(lesson.submit(0) == "ignored", "Must listen first")
	assert(lesson.listen())
	assert(lesson.submit(0) == "ignored", "No answers during demo")
	lesson.demo_finished()
	assert(lesson.submit(0) == "correct")
	assert(lesson.submit(7) == "retry")
	assert(lesson.score == 0 and lesson.answer_index == 0 and lesson.mistakes == 1)
	for round_number in range(3):
		if round_number > 0: lesson.listen(); lesson.demo_finished()
		for note in lesson.melody(): lesson.submit(note)
	assert(lesson.phase == "complete" and lesson.score == 115 and lesson.stars == 2 and lesson.unlocked() == 3)
	var restored = Rules.new()
	restored.restore(lesson.progress())
	assert(restored.unlocked() == 3 and restored.total() == 195)
	assert(restored.begin(2))
	for round_number in range(3):
		restored.listen(); restored.demo_finished()
		for note in restored.melody(): restored.submit(note)
	assert(restored.total() == 200, "Replays replace best scores, not accumulate")
	assert(restored.begin(3))
	for round_number in range(3):
		restored.listen(); restored.demo_finished()
		for note in restored.melody(): restored.submit(note)
	assert(restored.score == 150 and restored.stars == 3 and restored.total() == 350)
	restored.begin(1)
	assert(restored.total() == 350, "Retrying preserves completed progress")
	var bad = Rules.new()
	for corrupt in [null, [], {"version": 9}, {"version":1,"records":[{}, {}, {}]}, {"version":1,"records":[{"complete":true,"score":"bad","stars":3}, {}, {}]}]: bad.restore(corrupt)
	assert(bad.unlocked() == 1 and bad.total() == 0)
	print("LESSON RULES: PASS — stage locks, unique points, mistakes, stars, best scores, restoration, corrupt saves")
	quit()
